# Generated by Django 5.1.1 on 2024-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mystat'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/image/', verbose_name='image'),
        ),
    ]
