# Generated by Django 5.1.1 on 2024-10-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutme_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technolgy',
            new_name='Technology',
        ),
    ]
