# Generated by Django 5.1.1 on 2024-10-11 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_banner_aboutme_cv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='recommended_social/')),
                ('recommend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recommend')),
            ],
        ),
    ]
