# Generated by Django 5.1.1 on 2024-10-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_recommended_social'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommended_social',
            new_name='RecommendedSocial',
        ),
    ]
