# Generated by Django 5.1.1 on 2024-10-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_recommended_social_recommendedsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
    ]
